version: '3'

services:
###> doctrine/doctrine-bundle ###
  php:
    container_name: template_php
    build:
      context: .docker/php
    volumes:
      - ./:/var/www/
    networks:
      - symfony

  nginx:
    container_name: nginx
    build:
     context: .docker/nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
      - "4430:443"
    networks:
      - symfony

  mysql:
    image: 'mysql:8.0'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_DATABASE: 'main'
      MYSQL_USER: 'mysql'
    ports:
      - 3306:3306
    networks:
      - symfony


volumes:
  db-data:
  #    driver: local
  postgres-app-data:
  #    driver: local

networks:
  symfony:
